### PR TITLE
Filter out validated gnu test files.

### PR DESCRIPTION
**Pull request by Incarnation-p-lee**
* Temporarily place validated test files to auto-generated/gnu-overloaded-tests-validated.

Signed-off-by: Pan Li <pan2.li@intel.com>

### CODE REVIEW

**Review by eopXD — COMMENTED** [review]
I suggest a separate place rather than inside `auto-generated`, since my understanding is that this is extracted files that GCC current support and hence is not the full generation.

**Comment by Incarnation-p-lee** [comment]
How about `validated/gnu-overloaded-tests/vadc.C` ?

**Comment by eopXD** [comment]
> How about `validated/gnu-overloaded-tests/vadc.C` ?

I think this can be anything of your choice, since this is temporary. Eventually we want gcc to target something under `auto-generated`, right :)

**Comment by Incarnation-p-lee** [comment]
> > How about `validated/gnu-overloaded-tests/vadc.C` ?
> 
> I think this can be anything of your choice, since this is temporary. Eventually we want gcc to target something under `auto-generated`, right :)

Yes, exactly. Let me refine this PR.

**Comment by Incarnation-p-lee** [comment]
Updated, please help to continue the review. Thank you and have a nice day, ;)!

**Comment by Incarnation-p-lee** [comment]
@eopXD Kindly remind for related PR, any questions or concerns please feel free to let me know.

**Comment by Incarnation-p-lee** [comment]
Kindly remind for this one, #212 and #213.

**Review by eopXD — APPROVED** [review]
LGTM

**Comment by Incarnation-p-lee** [comment]
> LGTM

Great! Thank you!

**Pull request merged**
