### PR TITLE
Support vmv.v.v and vmerge.vvm for bf16 with `zvfbfmin`

### PR DESCRIPTION
**Pull request by 4vtomat**
Resolve: https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/349

### CODE REVIEW

**Review by kito-cheng — COMMENTED** [review]
bf16 should able to support vmv.v.f as well, I mean that could hold in FPR in theory, (w/ and w/o zfbhmin)

**Comment by 4vtomat** [comment]
> bf16 should able to support vmv.v.f as well, I mean that could hold in FPR in theory (both for w/ and w/o zfbhmin)

Updated!

**Review by kito-cheng — APPROVED** [review]
LGTM, but please make sure it's merge-able before you click merge :P

**Comment by jerryzj** [comment]
Please use `make yapf-format`

**Pull request merged**
