### PR TITLE
Define new RVV C intrinsic API for bf16 type

### PR DESCRIPTION
**Pull request by joshua-arch1**
As is duscussed in https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/223, the BF16 Extension has recently been proposed and we need to define new intrinsics for convert instruction with bf16 type as well as vfwmaccbf16 in Zvfbfwma Extenstion.

### CODE REVIEW

**Comment by eopXD** [comment]
Thank you for the pull request. Please modify the generator (`rvv-intrinsic-generator`) under to drive the automated generation.

**Comment by joshua-arch1** [comment]
> modify the generator (`rvv-intrinsic-generator`) under to drive the automated generation.

I have updated my pull request by modifying rvv-intrinsic-generator in https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/229

**Comment by eopXD** [comment]
May you have the two PR-s merged into one so the CI can run and verify it.

Thank you again!

**Comment by joshua-arch1** [comment]
> May you have the two PR-s merged into one so the CI can run and verify it.
> 
> Thank you again!

I think this PR can be abandoned since all the changes in rvv-intrinsic-generator have been commited in the pull request https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/229.

**Pull request closed without merging**
