### PR TITLE
Fix filename for API testing

### PR DESCRIPTION
**Pull request by eopXD**
The filenames was originally parsed with code like the following, probably a less maintainable way we want.

```
test_file_name = f"{overloaded_func_name.split('_')[3]}.c"
```

This PR fixes this by passing the actual mnemonic as a parameter and assigning it as the filename. Files are deleted / added due to this change, but the actual contents of the unit-test don't change.

### CODE REVIEW

**Comment by eopXD** [comment]
Landing this implies to adjust the test cases under llvm-project too to keep them in-sync.

**Review by kito-cheng — COMMENTED** [review]
Maybe encoding that info to inst_info?

**Comment by eopXD** [comment]
> Maybe encoding that info to inst_info?

Good point, changed 1st commit to reuse mnemonic already recorded under `inst_info`.

**Review by kito-cheng — APPROVED** [review]
LGTM

**Pull request merged**
