### PR TITLE
Add checker for gnu auto generated test cases

### PR DESCRIPTION
**Pull request by yulong-plct**
This PR add the checker for gnu cases that can help test intrinsic's correctness.
I did it together with @Incarnation-p-lee and @xl0714.
Please review it. Thanks! @eopXD

### CODE REVIEW

**Comment by eopXD** [comment]
Looks good, but I guess this is dependent on #280 for us to verify your test cases now?

**Comment by yulong-plct** [comment]
The PR #279 relies on this PR to complete the test. @eopXD

**Comment by eopXD** [comment]
> The PR #279 relies on this PR to complete the test. @eopXD

Let's add the commit to add workflow here and land it in whole?

**Comment by yulong-plct** [comment]
Please land this PR first, because the checker is added in every gnu case. After that, the workflow in the PR #279 is effective.

**Comment by yulong-plct** [comment]
Please land this PR first, because the checker is added in every gnu case. After that, the workflow in the PR #279 is effective.

**Review by eopXD — APPROVED** [review]

**Pull request merged**
