### PR TITLE
Add bibliography

### LINKED ISSUE #312: Create bibliography from reference section
Create a bibliography that follows RISC-V standards by using the existing Reference section in intrinsics doc.

### PR DESCRIPTION
**Pull request by rofirrim**
This fixes #312

### CODE REVIEW

**Comment by rofirrim** [comment]
I suggest to drop the numerous references in the text to the RVV itself unless there is a mechanism to link sections of the RVV specification.

I am aware asciidoc documents a mechanims to cross-reference documents but I presume it'd require to have the RISC-V ISA manual checked out at some point?

**Comment by kersten1** [comment]
Hoping that when we get HTML building and loaded into a framework, the links can become more immediately. Otherwise, yes, agree that dropping the number of links is a good thing. 

I'm also working to get the repos that are still using "master" to move to "main". That may cause some broken links. 

Otherwise, approved!

**Review by kersten1 — APPROVED** [review]

**Review by kito-cheng — APPROVED** [review]
LGTM :)

**Comment by rofirrim** [comment]
Rebase on top of recent changes.

**Pull request merged**
